
version: '3'

services:
        wordpress: 
            image: wordpress:latest            
            ports:
                - 192.168.8.101:1995:80 
            environment:
                WORDPRESS_DB_HOST: db
                WORDPRESS_DB_USER: admin
                WORDPRESS_DB_PASSWORD: mananx22
                WORDPRESS_DB_NAME: wordpress
            volumes:
                - wordpress_data2:/var/www/html
                - /tmp/wordpress/wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini      
                - /tmp/wordpress/duplicator-pro:/var/www/html/wp-content/plugins/duplicator-pro
                
        db:
            image: mysql:5.7            
            environment:
                MYSQL_DATABASE: wordpress
                MYSQL_USER: admin
                MYSQL_PASSWORD: mananx22
                MYSQL_ROOT_PASSWORD: 'manan'      
            volumes:
                - mysql_data:/var/lib/mysql
                
        
        phpmyadmin:
            image: phpmyadmin
            ports:
             - 192.168.8.101:9999:80
            environment:
             - PMA_ARBITRARY=1

volumes:
  wordpress_data2: 
  mysql_data:

# Remember, this docker compose doesnt affect mysql root password in any way
# even after wordpress backup has been restored. the root password remains what we have entered inm docker compose

# volumes & services are indent at same

# if wordpress ask for ftp, add this line to top of wpconfig ->  define( 'FS_METHOD', 'direct' );